// AUTH ACTIONS
export const REGISTER_EMAIL_CHANGED = 'REGISTER_EMAIL_CHANGED';
export const REGISTER_NAME_CHANGED = 'REGISTER_NAME_CHANGED';
export const REGISTER_PASSWORD_CHANGED = 'REGISTER_PASSWORD_CHANGED';
export const REGISTER_SUBMIT_FORM = 'REGISTER_SUBMIT_FORM';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';


// RESTAURANT ACTION
export const RESTAURANT_FETCH_ALL = 'RESTAURANT_FETCH_ALL';
export const RESTAURANT_FETCH_ALL_MENU = 'RESTAURANT_FETCH_ALL_MENU';
export const RESTAURANT_FETCH_MENU = 'RESTAURANT_FETCH_MENU';
export const RESTAURANT_FETCH_BY_ID = 'RESTAURANT_FETCH_BY_ID';
export const RESTAURANT_FETCH_BY_TYPE = 'RESTAURANT_FETCH_BY_TYPE';

// CART ACTION

export const cartActions = {
    FETCH_CART_ITEMS: 'FETCH_CART_ITEMS',
    UPDATE_CART_ITEM: 'UPDATE_CART_ITEM',
    UPDATE_CART_ITEM_QTY: 'UPDATE_CART_ITEM_QTY',
    DELETE_CART_ITEM: 'DELETE_CART_ITEM',
    SAVE_NEW_CART: 'SAVE_NEW_CART',
    SAVE_ITEM_INFO: 'SAVE_ITEM_INFO',
    CLEAN_CART_ITEMS: 'CLEAN_CART_ITEMS'
}

// ORDER ACTION

export const orderActions = {
    CREATE_ORDER: 'CREATE_ORDER',
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    // UPDATE_CART_ITEM: 'UPDATE_CART_ITEM',
    // UPDATE_CART_ITEM_QTY: 'UPDATE_CART_ITEM_QTY',
    // DELETE_CART_ITEM: 'DELETE_CART_ITEM',
    // SAVE_NEW_CART: 'SAVE_NEW_CART',
    // SAVE_ITEM_INFO: 'SAVE_ITEM_INFO',
    // CLEAN_CART_ITEMS: 'CLEAN_CART_ITEMS'
}
